### PR TITLE
Camera and player fix

### PR DESCRIPTION
**Pull request by lawin666**
We have added a camera node to the player scene that follows the players movement. We have also resized the player to fit the maps dimensions. We have also centered the players collision shape and sprite position in the scene.

### CODE REVIEW

**Comment by Tobeast1** [comment]
I think it's good

**Comment by Tobeast1** [comment]
> This depends on #6 right?

No, it is independent

**Comment by Tobeast1** [comment]
> This depends on #6 right?

No, this is an independent fix that centers the players position in player.tscn and adds a camera that will follow the player to the player scene.

**Review by xix-xeaon — CHANGES_REQUESTED** [review]
Why does this PR remove the hurtbox from the player?

**Pull request closed without merging**
