### PR TITLE
Mob spawning

### PR DESCRIPTION
**Pull request by DRubnnn**
added mob spawning around the player ca 900 pixels from the camera edge once every second in a rectangular shape.

### CODE REVIEW

**Comment by lawin666** [comment]
There is no game.tscn when I tested it and there is an error when I start the mob_spawning.tscn. You can create and put both mob_spawning.tscn and mob_spawning.gd in a folder or put them in the mob folder for less confusion.

**Review by ExclusiveKnight — CHANGES_REQUESTED** [review]
Please sync your fork so it's up to date with the [upstream repository](https://github.com/xixs-students/IT23-game). Overall, the PR should work just fine.

**Comment by DRubnnn** [comment]
To clarify, I intentionaly did not add a game scene, this does not depend on a game scene so you need to make one yourself in order to playtest.

**Review by xix-xeaon — APPROVED** [review]
This PR is better than #28 because of its modularity. With this implementation we can create alternative spawners and switch them out as needed, or it could be upgraded with settings for spawn rate, activation times, type of monster etc. Then multiple spawners could be added to the game scene (with different settings).

It would've been better if details on how to test it, and how it was intended to be used, were included, but #28 doesn't have any discription at all.

There is however a significant bug in this implementation but since none of you have discovered it I'll merge it as is.

**Pull request merged**
