### PR TITLE
Weapon able to target the mobs

### PR DESCRIPTION
**Pull request by ra1nns**
Added bullets to the weapon and put it on the player. Also made it so the weapon automatically targets the mobs.

### CODE REVIEW

**Comment by Snurrigt1** [comment]
The gun is still being shot if there aren't any enemies detected. Also see if you can do anything about the gun rotation as it looks weird when its upside down.

**Comment by ligamesh123** [comment]
I think should change the range of bullet in the same range with the camera of player so bullet will  be deleted when it went out of camera .

**Comment by nataisacat** [comment]
can you make the bullet firing speed more fast? because I think players won't be able to survive if there are too many monsters around

**Comment by ra1nns** [comment]
> I think you should change the range of bullet in the same range with the camera of player so bullet will be deleted when it went out of camera .

It already does that problem is if you move towards the bullet you will see it get removed which might confuse people for it being to short

**Comment by Tobeast1** [comment]
You can use get_overlapping bodies on the shoot() function the same way you did on the _physics_process function to make the gun shoot only when there are mobs nearby. (See row 17 & 18)
image

**Comment by ra1nns** [comment]
will do

**Review by Snurrigt1 — APPROVED** [review]

**Pull request merged**
