### PR TITLE
Pine tree sprite change and organized tree folder structure

### PR DESCRIPTION
**Pull request by Tobeast1**
I have changed the pine_tree.tscn sprite to be an animated pixel tree. I have also made the tree bigger and organized the tree folder into two folders, Assets and Scenes.

### CODE REVIEW

**Comment by Tobeast1** [comment]
Pine Tree - GREEN_TEAL  - 0000

This is the new texture

**Comment by ligamesh123** [comment]
I think you should change the order between AnimatedSprite2D and CollisionShape2D so we can see more clearly and i think you should change the storlek of collisionshape2d like that so player can go through  the tree when it behind the tree.
Skärmbild 2024-03-13 144022

**Comment by Tobeast1** [comment]
I have reset the tree's position that had been changed by mistake beforehand. The shadow of the tree is now more subtle and wider. I have changed the node structure so that the collisionshape is visible when in the editor. Lastly i have changed the collisionshape from a Rectangleshape to a Capsule shape so the player won't get stuck.

**Comment by ligamesh123** [comment]
It seem mergable right now for my opinion.

**Comment by Tobeast1** [comment]
@Snurrigt1 @DRubnnn can you merge this?

**Review by Snurrigt1 — APPROVED** [review]

**Review by Snurrigt1 — APPROVED** [review]

**Pull request merged**
