### PR TITLE
Add pause menu

### PR DESCRIPTION
**Pull request by ExclusiveKnight**
Pause/Unpause button is the "P" key. You can unpause with "P" while in the pause menu.

### CODE REVIEW

**Review by xix-xeaon — COMMENTED** [review]
Why is the code divided into both `toggle_pause_menu` and `_on_visibility_changed`? It seems pausing and showing go should go together.

**Comment by ExclusiveKnight** [comment]
> Why is the code divided into both `toggle_pause_menu` and `_on_visibility_changed`? It seems pausing and showing go should go together.

Yeah sorry about that, that's my bad on my end. I will change this ASAP. Thanks for mentioning me that.

**Comment by ra1nns** [comment]
Very nice doesn't seem to be any problems when i tried it.

**Comment by lawin666** [comment]
It seems good to me. I guess we should merge this one.

**Comment by DRubnnn** [comment]
is there any reason its not on the esc key? feels maybe a bit more fitting

**Comment by ExclusiveKnight** [comment]
> is there any reason its not on the esc key? feels maybe a bit more fitting

Yes, I agree that it's fitting because most games have it set to ESC key. @Tobeast1 asked me a similar question on Discord on why I didn't make the pause button the ESC key, and here's my answer to his question:
> because we don't know if the game will run on browser or not
> if you fullscreen the game in the browser and you press esc then you will leave fullscreen mode

I hope you understand why I decided to set it to the "P" key instead.

**Review by Snurrigt1 — APPROVED** [review]

**Pull request merged**
