### PR TITLE
First game scene with player

### PR DESCRIPTION
**Pull request by ligamesh123**

### CODE REVIEW

**Comment by Snurrigt1** [comment]
Game.tscn does not need its own folder at this moment. Put it in the root directory so it's easier to find when we have many folders.

**Comment by ligamesh123** [comment]
I have moved game.tscn to root

**Comment by Tobeast1** [comment]
Remove the enemy from the scene, they will have their own spawn point that will be decided by a script that will be added later.

**Comment by lawin666** [comment]
Instead of doing three different things in the same pull request, you should do two more pull requests one for the ghost mob and one for the main-menu.gd itself instead for less confusion.

**Review by xix-xeaon — CHANGES_REQUESTED** [review]
The ghost should not be part of this PR, it's already in #10.

**Comment by ligamesh123** [comment]
I have updated code from main_menu.gd and I have deleted ghost_scene from this branch.

**Comment by Tobeast1** [comment]
I think it's ready for merging, this is a core scene for the development of the rest of the game.

**Comment by lawin666** [comment]
Now this looks mergeable and it's acceptable.

**Review by xix-xeaon — APPROVED** [review]
Yeah, this is fine now!

**Pull request merged**
