### PR TITLE
Fixed mob bug

### PR DESCRIPTION
**Pull request by DRubnnn**
Fixed a bug with the teleporting mobs. since the mods spawned under the node that teleports the mobs teleported with thw player, that has now been fixed.

To test you must drag it in to the game

### CODE REVIEW

**Comment by DNQ4** [comment]
Seems to be working fine now.

**Comment by ligamesh123** [comment]
I think you should put the Spawn.scene to the Game.scene so the code will work when we play the main scene.

**Comment by Snurrigt1** [comment]
Put mob spawning in its own folder

**Comment by ligamesh123** [comment]
Before it merged 

> Put mob spawning in its own folder

I agree with it , before it merge u shoud put .tscn file and .script file to one folder so it good for sortering.

**Comment by DRubnnn** [comment]
Added them to a folder. Thanks for the suggestions!

**Review by Snurrigt1 — APPROVED** [review]

**Pull request merged**
