### PR TITLE
Add enemy scene

### PR DESCRIPTION
**Pull request by ligamesh123**
I added one ghost enemy-scene by using Character2D, Sprite2D and CollisionShape2D.

### CODE REVIEW

**Comment by Tobeast1** [comment]
Can you put the .tscn file in the Ghost folder?

**Comment by lawin666** [comment]
I agree with @Tobeast1 about putting .tscn file in the folder instead for less clutter.

**Comment by ligamesh123** [comment]
@Tobeast1 I have change file location to same folder Ghost.

**Comment by xix-xeaon** [comment]
This enemy will need a behaviour (script). Have a look at #9 and up

**Comment by Snurrigt1** [comment]
> Refe

How can we test it? When creating a node2d scene and adding the player.tscn and enemy.tscn nodes the game crashes.

**Comment by Snurrigt1** [comment]
I believe you are missing an autoload in your script.

**Comment by xix-xeaon** [comment]
In #9 a singelton was created for scripts to be able to reference the player, use that. It also introduced a mob folder where you can put the ghost. You should probably rebase on that.

**Review by xix-xeaon — CHANGES_REQUESTED** [review]
In #9 a singelton was created for scripts to be able to reference the player, use that. It also introduced a mob folder where you can put the ghost. You should probably rebase on that.

**Comment by ligamesh123** [comment]
Update ghost.gd script change player to Global.player

**Comment by xix-xeaon** [comment]
I don't think the enemy should be added to the game scene.

**Comment by ligamesh123** [comment]
> I don't think the enemy should be added to the game scene.

I have deleted enemy from game-scene

**Review by xix-xeaon — APPROVED** [review]

**Pull request merged**
